article environnement Quarkus avec WSL
SCIAM-FR/sciam-fr.github.io pull request #100
Opened 2024-09-18 13:54 UTC by pcheucle

## Suivi revue article

| Relecteur                          | Statut                                                                        | Validation                 | 
|------------------------------------|-------------------------------------------------------------------------------|----------------------------|
| @antoinesd                         | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| @jmdoudoux-sciam                   | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| Ajouter la personne de votre choix | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |

## Points à prendre en compte durant la relecture
- Forme
    - tournures, oublis, passages trop lourds/indigestes, orthographe, grammaire
    - méta-données : auteur, résumé
- Fond
- Légal
    - Originalité de l'article, source des images
- SEO

2024-09-19 07:35 UTC, jmdoudoux-sciam requested changes

2024-09-19 07:35 UTC, jmdoudoux-sciam commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> += Créez votre environnement de développement Quarkus en 10 minutes avec WSL
Peut être préciser que c'est la version 2 de WSL qui est concerné dans l'article ?

2024-09-19 07:35 UTC, jmdoudoux-sciam commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +Il est très frequent d'avoir à construire une image container en vue de la déployer dans une infrastructure type Kubernetes.
```suggestion
Il est très fréquent d'avoir à construire une image container en vue de la déployer dans une infrastructure type Kubernetes.

```

2024-09-19 07:35 UTC, jmdoudoux-sciam commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +Développer avec Quarkus sous Linux offre certains avantages comme le fait de bénéficier d’un système de fichiers sensible à la casse par défaut, de pouvoir installer plus facilement les prérequis à l
exécutable natif sous Linux

2024-09-19 07:35 UTC, jmdoudoux-sciam commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +La distribution Linux installée par défaut est Ubuntu, mais il est possible de spécifier une autre distribution Linux.
Parmi celles proposée/supportée par Microsoft

2024-09-19 07:35 UTC, jmdoudoux-sciam commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +cd code-with-quarkus
il manque surement des détails ou des infos pour comprendre d'où vient le sous répertoire code-with-quarkus

2024-09-19 07:35 UTC, jmdoudoux-sciam commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +== La build d'un projet Quarkus avec Quarkus CLI
comme le genre est impersonnel en anglais on peut éventuellent mettre le masculin ou le féminin mais généralement on utilise le masculin pour build (le build)

2024-09-19 07:35 UTC, jmdoudoux-sciam commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +Puis, nous vérifions le bon fonctionnement de l'application en allant sur http://localhost:8080/hello.
sous Windows ? ou sous Linux ?

2024-09-19 07:35 UTC, jmdoudoux-sciam commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +Un des principaux avantages de Quarkus est de pouvoir compiler nativement une application afin que celle-ci démarre plus rapidement et soit moins consommatrice en ressources CPU et RAM.
C'est vrai mais mais c'est souvent les bons côtés de la compilation native qui sont mis en avant et rarement les mauvais (et il y en a plein) mais ce n'est pas l'objet de ton article

2024-09-19 07:35 UTC, jmdoudoux-sciam commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +On notera que le démarrage de l'application est plus rapide que dans le cas d'un compilation classique.
```suggestion
On notera que le démarrage de l'application est plus rapide que dans le cas de l'exécution dans une JVM.

```

2024-09-19 07:35 UTC, jmdoudoux-sciam commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +Afin de pouvoir générer une image container, nous avons besoin d'un environnement d'exécution tel que Podman.
```suggestion
Afin de pouvoir générer une image, nous avons besoin d'un environnement d'exécution tel que Podman.

```

2024-09-19 07:35 UTC, jmdoudoux-sciam commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +Afin de pouvoir générer une image container, nous avons besoin d'un environnement d'exécution tel que Podman.
ou remplacer container par OCI

2024-09-19 07:35 UTC, jmdoudoux-sciam commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +Cette dernière permet la génération d'images container via Podman.
idem commentaire précédent

2024-09-19 07:35 UTC, jmdoudoux-sciam commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +Une fois la phase de build terminée, nous pouvons démarrer l'image container dans Podman :
```suggestion
Une fois la phase de build terminée, nous pouvons démarrer un conteneur à partir de l'image dans Podman :

```

2024-09-19 07:35 UTC, jmdoudoux-sciam commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +podman run localhost/user/code-with-quarkus:1.0.0-SNAPSHOT
il n'y a pas besoin de mapping du port 8080 ?

2024-09-19 07:35 UTC, jmdoudoux-sciam commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +Les outils nécessaires pour pouvoir développer avec Quarkus sont installés de manière transparente, sans impacter la machine Windows.
sans impacter la machine Windows : ????

2024-09-20 08:48 UTC, pcheucle commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> += Créez votre environnement de développement Quarkus en 10 minutes avec WSL
Précision ajoutée dans l'intro

2024-09-20 08:59 UTC, jmdoudoux-sciam approved these changes

2024-09-23 13:14 UTC, dborie commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +Puis, nous vérifions le bon fonctionnement de l'application en allant sur http://localhost:8080/hello depuis Windows.
Peut être bien de préciser que localhost est un bonus apporter par MS et que 127.0.0.1 ne marchera pas

2024-09-23 13:14 UTC, dborie commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +quarkus image build podman --native -Dquarkus.native.container-build=true
-Dquarkus.native.container est optionel et ne sert qu'à se passer des outils de build

2024-09-24 09:33 UTC, pcheucle commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +sudo apt-get install zip unzip
:+1:

2024-09-25 08:52 UTC, pcheucle commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +== L'installation de Visual Studio Code pour développer en remote depuis WSL
Merci pour l'info.
Pour moi, ce problème est lié à un usage non recommandé de WSL2.
WSL2 utilise un serveur (9P) pour rendre les fichiers accessibles dans Windows. Je ne pense pas que les performances soient suffisantes pour travailler dans un IDE sur un projet ouvert depuis le file system Windows.
Dans mon article, j'encourage à utiliser le mode client serveur, je ne pense donc pas nécessaire de parler de cette issue.

2024-09-25 08:56 UTC, pcheucle commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +Enfin, développer dans WSL depuis Windows de façon productive est rendu possible grâce au mode remote de Visual Studio Code.
En effet, c'est proposé par la version Ultimate de Idea.
Pas disponible dans Eclipse, mais il reste toujours la possibilité d'ouvrir Eclipse dans WSL, et d'avoir la UI dans Windows avec WSLg, et c'est supporté par défaut dans Windows 11 (ce qui est également un mode remote client serveur).

2024-09-25 09:00 UTC, pcheucle commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +L'environnement Linux ainsi que les outils nécessaires pour pouvoir développer avec Quarkus sont installés de manière transparente, sans nécessiter l'installation d'une machine virtuelle traditionnel
Je suis d'accord à 100 %, mais je garde ça plutôt pour un REX, mon article étant plus un guide/tuto.

2024-09-26 14:37 UTC, pcheucle commented on _posts/2024-09-13-env-quarkus-wsl.adoc
> +quarkus image build podman --native -Dquarkus.native.container-build=true
Le but ici est de présenter la possibilité de builder nativement l'appli dans podman plutôt qu'en local.
Je vais détailler un peu plus cette partie là afin d'être plus clair.

2024-10-02 05:33 UTC, antoinesd approved these changes
LGTM

2024-10-02 05:33 UTC, merged