nouveautes-java-23-partie2
SCIAM-FR/sciam-fr.github.io pull request #108
Opened 2024-10-21 14:48 UTC by jmdoudoux-sciam

## Suivi revue article

| Relecteur                          | Statut                                                                        | Validation                 | 
|------------------------------------|-------------------------------------------------------------------------------|----------------------------|
| @antoinesd                         | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| @CodeSimcoe                    | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| Ajouter la personne de votre choix | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |

## Points à prendre en compte durant la relecture
- Forme
    - tournures, oublis, passages trop lourds/indigestes, orthographe, grammaire
    - méta-données : auteur, résumé
- Fond
- Légal
    - Originalité de l'article, source des images
- SEO

2024-10-21 15:22 UTC, CodeSimcoe requested changes
QQ typos mineurs

2024-10-21 15:28 UTC, jmdoudoux-sciam commented on _posts/2024-10-18-nouveautes-java-23-partie2.adoc
> +Malheureusement, de nombreuses bibliothèques utilisent `sun.misc.Unsafe` puisque la visibilité de cette classe est `public`, mais toutes n’effectuent pas les vérifications de sécurité requises.
cf notre discussion Teams

2024-10-22 11:59 UTC, antoinesd requested changes

2024-10-22 11:59 UTC, antoinesd commented on _posts/2024-10-18-nouveautes-java-23-partie2.adoc
> +Comme le nom de la classe l’indique, la plupart de ces opérations ne sont pas sûres. Cependant ces méthodes peuvent aider à augmenter les performances dans certains scénarios spécifiques, mais unique
```suggestion
Comme le nom de la classe l’indique, la plupart de ces opérations ne sont pas sûres. Cependant, ces méthodes peuvent aider à augmenter les performances dans certains scénarios spécifiques, mais uniquement si des vérifications exhaustives de sécurité sont effectuées.
```

2024-10-22 11:59 UTC, antoinesd commented on _posts/2024-10-18-nouveautes-java-23-partie2.adoc
> +Pour les atteindre, la JEP inclue :
```suggestion
Pour les atteindre, la JEP inclus :
```

2024-10-22 11:59 UTC, antoinesd commented on _posts/2024-10-18-nouveautes-java-23-partie2.adoc
> +La grande majorité des développeurs Java n'utilisent pas explicitement `sun.misc.Unsafe` dans leur propre code mais de très nombreuses applications en dépendent, directement ou indirectement à cause
```suggestion
La grande majorité des développeurs Java n'utilisent pas explicitement `sun.misc.Unsafe` dans leur propre code, mais de très nombreuses applications en dépendent, directement ou indirectement à cause des nombreuses bibliothèques qui l’utilisent.
```

2024-10-22 11:59 UTC, antoinesd commented on _posts/2024-10-18-nouveautes-java-23-partie2.adoc
> +Il est a noté que c’est la première fois qu’une fonctionnalité en preview n’est pas reconduite dans une version suivante du JDK.
```suggestion
Il est à noter que c’est la première fois qu’une fonctionnalité en preview n’est pas reconduite dans une version suivante du JDK.
```

2024-10-22 11:59 UTC, antoinesd commented on _posts/2024-10-18-nouveautes-java-23-partie2.adoc
> +* une fonctionnalité en preview, est spécifique pour une version du JDK, et donc si une fonctionnalité n’est pas reconduite en preview ou promue en standard, elle doit être retirée
```suggestion
une fonctionnalité en preview est spécifique pour une version du JDK, et donc si une fonctionnalité n’est pas reconduite en preview ou promue en standard, elle doit être retirée
```

2024-10-22 11:59 UTC, antoinesd commented on _posts/2024-10-18-nouveautes-java-23-partie2.adoc
> +Depuis Java 1.2, la méthode `ThreadGroup.stop()` était marquée comme dépréciée car le concept d’arrêt d’un groupe de threads était mal implémenté dès le départ.
```suggestion
Depuis Java 1.2, la méthode `ThreadGroup.stop()` était marquée comme dépréciée, car le concept d’arrêt d’un groupe de threads était mal implémenté dès le départ.
```

2024-10-22 11:59 UTC, antoinesd commented on _posts/2024-10-18-nouveautes-java-23-partie2.adoc
> +Dans le JDK 14, ces méthodes été dépréciées pour suppressions (deprecated for removal).
```suggestion
Dans le JDK 14, ces méthodes ont été dépréciées pour suppressions (deprecated for removal).
```

2024-10-22 11:59 UTC, antoinesd commented on _posts/2024-10-18-nouveautes-java-23-partie2.adoc
> +Si un module utilise une clause requires `jdk.random` alors il faut la supprimer pour permettre sa compilation en Java 23 puisque le module `jdk.random` est supprimé et que le module `java.base` est
```suggestion
Si un module utilise une clause requires `jdk.random` alors, il faut la supprimer pour permettre sa compilation en Java 23 puisque le module `jdk.random` est supprimé et que le module `java.base` est automatiquement requis.
```

2024-10-22 11:59 UTC, antoinesd commented on _posts/2024-10-18-nouveautes-java-23-partie2.adoc
> +L’objectif de la https://openjdk.org/jeps/471[JEP 471] est d’encourager les développeurs à passer d’`Unsafe` à ces API plus sûres et prises en charge, améliorant ainsi la compatibilité avec les futur
```suggestion
L’objectif de la https://openjdk.org/jeps/471[JEP 471] est d’encourager les développeurs à passer d’`Unsafe` à ces API plus sûres et prises en charge, améliorant ainsi la compatibilité avec les futures versions du JDK tout en réduisant les risques de comportements erratiques ou de plantages.
```

2024-10-22 12:08 UTC, antoinesd approved these changes
LGTM

2024-10-22 12:10 UTC, merged