Un design évolutif pour des solutions révolutionnaires
SCIAM-FR/sciam-fr.github.io pull request #116
Opened 2024-11-25 18:53 UTC by bmscomp

## Suivi revue article

| Relecteur                          | Statut                                                                        | Validation                 | 
|------------------------------------|-------------------------------------------------------------------------------|----------------------------|
| @antoinesd                         | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| @jmdoudoux-sciam                   | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |

## Points à prendre en compte durant la relecture
- Forme
    - tournures, oublis, passages trop lourds/indigestes, orthographe, grammaire
    - méta-données : auteur, résumé
- Fond
- Légal
    - Originalité de l'article, source des images
- SEO

2024-11-28 16:32 UTC, antoinesd requested changes

2024-11-28 16:32 UTC, antoinesd commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +], plutôt qu'une seule solution optimale.
```suggestion
, plutôt qu'une seule solution optimale.
```

2024-11-28 16:39 UTC, antoinesd requested changes
Cet article, mériterait une démarche beaucoup plus pédagogique.
Quelques remarques en vrac:

- Il faudrait commencer par expliquer de quoi tu vas parler dès le début au lieu de cette intro sur le big bang
- le prelude n'est là que pour donner une aprroximation du nombre d'atomes dans l'univers, ce n'est peut être pas la peine de raconter le big bang pour le rappeler
- Comme dit dans les commentaires, c'est très bizarre de parler de l'algo du voaygeur de commerce sans le nommer avant d'y faire référence. Moi j'en parlerai direct et ferait une section admonition note pour rappeler de quoi il s'agit
- La seconde partie m'a l'air nettement plus lisible même si je ne l'ai que sruvolée, j'attends une version pue retravaillée
- Les notes de bas de page c'est bien mais pas toujours indispensable, tu pourrais en transformer quelques une en admonition NOTE
- Essaye de faire une version avec une phrase pasr ligne comme recommandé dans la doc as code.

2024-11-28 19:56 UTC, bmscomp commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +Nous avons une séquence de lettres *``ABC``* et nous voulons trouver toutes les permutations possibles, c'est-à-dire
Je viens d'enlever cette partie, j'ai bien penser que les AE, ont role bcp plus important que de simple solution a certains problemes NP-Difficiles, je pense que parler de ces deux examples classiques limite un peu le scope

2024-11-28 20:02 UTC, bmscomp commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +== Prélude
J'ai fini par supprimer la section prelude

2024-11-28 20:04 UTC, bmscomp commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +Maintenant, nous devons trouver la meilleure solution pour le problème suivant :
Cette section n'est plus nécessaire. Il est tout à fait possible d'expliquer l'importance des AE sans faire référence à ces deux exemples

2024-11-28 20:05 UTC, bmscomp commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +NP (Non-deterministic Polynomial time); Example : Le célèbre problème du voyageur de commerce
C est un residue de la premiere version de documents qui survole juste le probleme TSP comme un probleme NP-Difficile avant de le detailler,

2024-11-28 20:46 UTC, bmscomp reviewed
@antoinesd, merci bcp pour la review, Je viens de mettre à jour ma pull request en enlevant la section Prelude ainsi que les deux exemples de permutation et de problème TSP. Cela réduit légèrement la perspective de l'article, mais ces exemples ne représentent qu'un détail mineur pour ce type d'algorithme, qui aborde des problèmes beaucoup plus significatifs.

2024-11-28 23:41 UTC, bmscomp commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +:page-excerpt:
Done

2024-12-10 17:02 UTC, antoinesd requested changes

2024-12-10 17:04 UTC, antoinesd requested changes
Article Très intéressant, mais quelques fautes et des répétionts. Je n'ai pas totalement fini la review, j'attends une version un peu plus aboutie.
Ce sertait aussi sympa si tu pouvais mettre un ou deux exempel de code (si c'est réaliste) dans la partie framework.

2024-12-14 23:35 UTC, bmscomp commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +Elle offre un ensemble d'outils pour résoudre des problèmes d'optimisation multi-objectifs.
Done

2024-12-16 21:34 UTC, bmscomp commented
@antoinesd, merci beaucoup pour la revue, je comprends plus l'effort qu'il me faut pour avoir quelque chose de plus correct, je viens de supprimer ou modifier quelques repetitions, pour l'example en  Java cela va demander encore quelques pages de plus

2025-02-06 16:10 UTC, antoinesd requested changes
Encore quelques typos

2025-02-06 16:21 UTC, antoinesd commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +Cet algorithme est conçu pour trouver des solutions optimales en équilibrant plusieurs objectifs contradictoires, tels que :
```suggestion
Cet algorithme est conçu pour trouver des solutions optimales en équilibrant plusieurs objectifs contradictoires, tels que :


```

2025-02-06 16:23 UTC, antoinesd commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +Bien qu'il soit souvent considéré comme un problème abstrait, il a des applications très concrètes dans de nombreux domaines
```suggestion
```

2025-03-04 16:39 UTC, jmdoudoux-sciam requested changes

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +=== Programmation génétique (PG)
```suggestion
=== Programmation Génétique (PG)

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +=== Algorithmes évolutionnaires multi-objectifs (MOEA)
```suggestion
=== Algorithmes Evolutionnaires Multi-Objectifs (MOEA)

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +* *Mutation*: La mutation dans *ED* est réalisée en combinant les différences entre des solutions (ou individus) pour créer de nouvelles solutions candidates.
```suggestion
* *Mutation* : la mutation dans *ED* est réalisée en combinant les différences entre des solutions (ou individus) pour créer de nouvelles solutions candidates.

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +* *Croisement (Recombinaison)* : L'opérateur de croisement combine la solution d'origine (parent) avec la solution mutante pour produire un nouvel individu.
```suggestion
* *Croisement (Recombinaison)* : l'opérateur de croisement combine la solution d'origine (parent) avec la solution mutante pour produire un nouvel individu.

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +* *Sélection* : Une fois que l'individu mutant (ou recombiné) a été généré, il est comparé à la solution originale, (c'est-à-dire son parent).
```suggestion
* *Sélection* : une fois que l'individu mutant (ou recombiné) a été généré, il est comparé à la solution originale, (c'est-à-dire son parent).

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +*Applications concrètes* : Optimisation des hyperparamètres dans les réseaux de neurones ou dans des systèmes où la solution est un vecteur continu, comme l'optimisation de la trajectoire d'un robot
```suggestion
Il existe plusieurs *applications concrètes*, telles que l'optimisation des hyperparamètres dans les réseaux de neurones ou dans des systèmes où la solution est un vecteur continu, comme l'optimisation de la trajectoire d'un robot autonome en utilisant des données sensorielles.

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +Le langage java est un choix populaire pour implémenter des algorithmes évolutionnaires en raison de sa simplicité, de sa robustesse, de ses performances, et de sa portabilité sur de nombreuses plate
```suggestion
Le langage Java est un choix populaire pour implémenter des algorithmes évolutionnaires en raison de sa simplicité, de sa robustesse, de ses performances, et de sa portabilité sur de nombreuses plateformes.

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +Face à un manque de moyens techniques et d'outils fiables, nous nous retrouvons toujours face une situation avec laquelle il est très difficile de réaliser d'optimiser de grandes applications basées
```suggestion
Face à un manque de moyens techniques et d'outils fiables, nous nous retrouvons toujours face une situation avec laquelle il est très difficile d'optimiser de grandes applications basées sur une architecture microservices.

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +=== Cas d'utilisation : Optimisation des architectures Kafka dans un environnement cloud
```suggestion
=== Cas d'utilisation : optimisation des architectures Kafka dans un environnement cloud

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +Dans un ou plusieurs clusters Kafka composés de plusieurs brokers par cluster, avec une infrastructure de communication cellulaire _5G_, des milliers de capteurs IoT, une diversité d'API utilisant di
```suggestion
Dans un ou plusieurs clusters Kafka composés de plusieurs brokers par cluster, avec une infrastructure de communication cellulaire _5G_, des milliers de capteurs IoT, une diversité d'API utilisant différents protocoles, ainsi que des milliers de microservices et d'applications, nous sommes confrontés à un problème d'optimisation particulièrement complexe.

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +Une approche intuitive serait de : prendre une architecture arbitraire `A1` avec une configuration des composants et service `C1`, effectuer un test réel et attendre les résultats après un certain dé
```suggestion
Une approche intuitive serait de prendre une architecture arbitraire `A1` avec une configuration des composants et service `C1`, effectuer un test réel et attendre les résultats après un certain délai. Ensuite, réaliser un benchmarking pour passer à une configuration `C2`, ce qui pourrait impliquer des modifications telles que la taille des machines, le nombre de brokers, le nombre de partitions, etc.

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +=== NSGA-II : Une approche évolutionnaire pour l’optimisation multi-objectifs
```suggestion
=== NSGA-II : une approche évolutionnaire pour l’optimisation multi-objectifs

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +==== Étapes principales de NSGA-II :
```suggestion
==== Étapes principales de NSGA-II

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +. **Initialisation** : Générer une population initiale de configurations aléatoires,
```suggestion
. **Initialisation** : générer une population initiale de configurations aléatoires,

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +. **Évaluation** : Mesurer les performances de chaque configuration selon les objectifs (latence, débit, etc.)
```suggestion
. **Évaluation** : mesurer les performances de chaque configuration selon les objectifs (latence, débit, etc.)

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +. **Tri par domination** : Classer les solutions en fonction de leur non-domination.
```suggestion
. **Tri par domination** : classer les solutions en fonction de leur non-domination.

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +. **Crowding distance** : Mesurer la diversité des solutions dans chaque rang de domination pour favoriser une exploration équilibrée.
```suggestion
. **Crowding distance** : mesurer la diversité des solutions dans chaque rang de domination pour favoriser une exploration équilibrée.

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +- Mutation : Nous ajoutons des modifications aléatoires, comme réduire ou augmenter la quantité de RAM,
```suggestion
- Mutation : nous ajoutons des modifications aléatoires, comme réduire ou augmenter la quantité de RAM,

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +. **Itérations** : Répéter le processus sur plusieurs générations pour faire converger la population vers une solution optimale.
```suggestion
. **Itérations** : répéter le processus sur plusieurs générations pour faire converger la population vers une solution optimale.

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +==== Avantages de NSGA-II :
```suggestion
==== Avantages de NSGA-II

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +- **Front de Pareto** : Permet d'obtenir un ensemble de solutions optimales, laissant aux décideurs le choix parmi plusieurs compromis entre les objectifs.
```suggestion
- **Front de Pareto** : permet d'obtenir un ensemble de solutions optimales, laissant aux décideurs le choix parmi plusieurs compromis entre les objectifs.

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +- **Efficacité computationnelle** : Réduit la complexité grâce à des mécanismes optimisés comme le tri rapide des solutions dominées.
```suggestion
- **Efficacité computationnelle** : réduit la complexité grâce à des mécanismes optimisés comme le tri rapide des solutions dominées.

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +- **Diversité des solutions** : Garantit une exploration équilibrée de l'espace des configurations.
```suggestion
- **Diversité des solutions** : garantit une exploration équilibrée de l'espace des configurations.

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +- **Adaptabilité** : Peut être appliqué à des problèmes complexes avec des objectifs multiples et contradictoires.
```suggestion
- **Adaptabilité** : peut être appliqué à des problèmes complexes avec des objectifs multiples et contradictoires.

```

2025-03-04 16:39 UTC, jmdoudoux-sciam commented on _posts/2024-11-16-un_design_par_evolution.adoc
> +En plus des classiques algorithmes génétiques, stratégies d'évolution, programmation génétique, elle propose des algorithmes évolutionnaires multi-objectifs (MOEA) comme NSGA-IIfootnote:nsga[*NSGA-II
```suggestion
En plus des classiques algorithmes génétiques, stratégies d'évolution, programmation génétique, elle propose des algorithmes évolutionnaires multi-objectifs (MOEA) comme NSGA-IIfootnote:nsga[*NSGA-II (Non-dominated Sorting Genetic Algorithm II)* est un algorithme génétique multi-objectifs largement utilisé en recherche opérationnelle et en informatique.

```

2025-03-05 20:58 UTC, antoinesd approved these changes
LGTM

2025-03-05 21:00 UTC, merged