Article sur Spring Boot et OpenAI
SCIAM-FR/sciam-fr.github.io pull request #43
Opened 2024-01-14 21:00 UTC by ricken07

## Suivi revue article

| Relecteur                          | Statut                                                                        | Validation                 | 
|------------------------------------|-------------------------------------------------------------------------------|----------------------------|
| @antoinesd                         | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| @jmdoudoux-sciam                   | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| Ajouter la personne de votre choix | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |

## Points à prendre en compte durant la relecture
- Forme
    - tournures, oublis, passages trop lourds/indigestes, orthographe, grammaire
    - méta-données : auteur, résumé
- Fond
- Légal
    - Originalité de l'article, source des images
- SEO

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> += Spring Boot et OpenAI - Une incursion dans l’AI générative
```suggestion

```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +:page-navtitle: Spring Boot et OpenAI - Une incursion dans l’AI générative
```suggestion
= Spring Boot et OpenAI - Une incursion dans l’AI générative
:page-navtitle: Spring Boot et OpenAI - Une incursion dans l’AI générative
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> += Qu’est-ce que Spring AI
```suggestion
== Qu’est-ce que Spring AI
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> += Générer le projet Spring Boot
```suggestion
== Générer le projet Spring Boot
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> += Le fichier pom.xml
```suggestion
== Le fichier pom.xml
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> += Configuration du projet
```suggestion
== La configuration du projet
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> += Le Controller
```suggestion
== Le Controller
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> += Les Modèles et la Température
```suggestion
== Les Modèles et la Température
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +== Les Modèles
```suggestion
=== Les Modèles
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +== Température
```suggestion
=== La notion de température
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> += Le Prompt
```suggestion
== Le Prompt
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> += Tester l'application
```suggestion
== Le test de l'application
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> += Conclusion
```suggestion
== Conclusion
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Voici à quoi ressemble mon projet Spring Boot générer (dans mon cas, j’ai utilisé IntelliJ IDEA).
```suggestion
Voici à quoi ressemble mon projet Spring Boot généré (dans mon cas, j’ai utilisé IntelliJ IDEA).
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +ce starter nous aide à mettre en place l’ensemble des dépendances et classes essentielles pour travailler
```suggestion
Ce starter nous aide à mettre en place l’ensemble des dépendances et classes essentielles pour travailler.
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Pour simplifier la génération de votre projet, vous pouvez utiliser le projet https://start.spring.io[spring initializr^] ou encore https://spring.io/projects/spring-cli[spring cli^], les starters so
```suggestion
Pour simplifier la génération de votre projet, vous pouvez utiliser le projet https://start.spring.io[Spring Initializr^] ou encore https://spring.io/projects/spring-cli[Spring Cli^], les starters sont disponibles pour aider à mettre en place les dépendances et les classes essentielles.
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Pour notre fichier de compilation, nous aurons besoin de l'artefact `spring-ai-openai-spring-boot-starter`
```suggestion
Pour notre projet, nous aurons besoin de l'artefact `spring-ai-openai-spring-boot-starter`
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Nous allons comprendre l'auto-configuration fournie par Spring Boot pour nous aider à maitriser et personnaliser la configuration des composants prochainement.
Je ne comprends pas cette phrase.
Remplacer prochainement par "dans un prochain article" ??

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Nous utilisant une version Snapshot du projet. Le projet Spring AI fournit des artefacts dans les dépôts Spring Milestone et Snapshot.
```suggestion
Nous utilisons une version Snapshot du projet. Le projet Spring AI fournit des artefacts dans les dépôts Spring Milestone et Snapshot.
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Vous devez ajouter des références aux référentiels Spring Milestone et/ou Snapshot dans votre fichier pom.xml
```suggestion
Vous devez ajouter des références aux référentiels Spring Milestone et/ou Snapshot dans votre fichier pom.xml.
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Pour un projet Maven, ajouté
```suggestion
Pour un projet Maven, il faut ajouter :
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Voici le contenu du fichier pom.xml de notre projet
```suggestion
Voici le contenu du fichier pom.xml de notre projet :
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Pour un projet Maven, ajouté
ou simplement ajoutez

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Pour obtenir la clé de l’API, créer un compte sur https://platform.openai.com/signup[la platform openai^] et générez une https://platform.openai.com/api-keys[API Keys^]
```suggestion
Pour obtenir la clé de l’API, créer un compte sur https://platform.openai.com/signup[la platform openai^] et générez une https://platform.openai.com/api-keys[API Keys^].
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Voici la configuration dans le fichier `application.yml`
```suggestion
Voici la configuration dans le fichier `application.yml` :
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Vous pouvez vous retrouver à configurer un fichier `application.properties`
```suggestion
Vous pouvez alternativement utiliser un fichier `application.properties`
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Nous allons utiliser `OpenAiChatClient` une implémentation de `ChatClient` pour OpenAI que vous pourrez injecter dans votre classe. Voici un exemple
```suggestion
Nous allons utiliser `OpenAiChatClient` une implémentation de `ChatClient` pour OpenAI que vous pourrez injecter dans votre classe. Voici un exemple :
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Nous allons utiliser `OpenAiChatClient` une implémentation de `ChatClient` pour OpenAI que vous pourrez injecter dans votre classe. Voici un exemple
```suggestion
Nous allons utiliser `OpenAiChatClient` une implémentation de `ChatClient` pour OpenAI que vous pourrez vous faire injecter via le constructeur dans votre classe. Voici un exemple
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Le modèle par défaut fournit par Spring AI est `gpt-3.5-turbo`, pour en savoirs plus sur les modèles, c'est par https://platform.openai.com/docs/models[ici^]
```suggestion
Le modèle par défaut fourni par Spring AI est `gpt-3.5-turbo`, pour en savoir plus sur les modèles, c'est par https://platform.openai.com/docs/models[ici^]
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +La notion de `température`; D'un point de vue technique, elle est étroitement associée à la notion d'échantillonnage, qui implique de choisir une réponse parmi plusieurs possibilités en fonction de l
```suggestion
D'un point de vue technique, la notion de `température` est étroitement associée à la notion d'échantillonnage, qui implique de choisir une réponse parmi plusieurs possibilités en fonction de leurs probabilités respectives. La température agit comme un paramètre de mise à l'échelle pour ces probabilités.
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +`Spring AI configure par défaut la température à 0,7`, un échantillonnage proportionnel aux probabilités du modèle, il représente un compromis entre la créativité et la cohérence.
```suggestion
`Spring AI configure par défaut la température à 0,7`, un échantillonnage proportionnel aux probabilités du modèle, qui représente un compromis entre la créativité et la cohérence.
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Supposons que vous utilisiez un modèle de langage génératif tel que GPT-3 ou 4. Dans ce cas, vous pourriez soumettre un exemple d'instruction tel que "écrit du code Java clean..." pour obtenir une ré
```suggestion
Supposons que vous utilisiez un modèle de langage génératif tel que GPT-3 ou 4. Dans ce cas, vous pourriez soumettre un exemple d'instruction tel que "écrit du code Java clean..." pour obtenir une réponse générée par le modèle. Le prompt agit comme le point initial pour l'IA, lui permettant de comprendre la nature de la tâche à effectuer.
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Spring AI nous fournit une classe `Prompt` qui sert de support structuré à une séquence d'objets `Message`, chacun représentant une partie du prompt complète.
```suggestion
Spring AI fournit la classe `Prompt` qui sert de support structuré à une séquence d'objets `Message`, chacun représentant une partie du prompt complet.
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Mais la méthode `generate` de `ChatClient` prend également un objet String comme paramètre qui ressemble à ci-dessous et renvoie simplement une chaine de caractère.
```suggestion
Une surcharge de la méthode `generate` de `ChatClient` prend également un objet de type String en paramètre et renvoie simplement une chaine de caractère, comme dans l'exemple ci-dessous :
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Pour tester l'application vous pouvez utiliser un client REST, dans mon cas j'utilise https://www.postman.com/[postman^]
```suggestion
Pour tester l'application, vous pouvez utiliser un client REST, dans mon cas j'utilise https://www.postman.com/[postman^]
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Voici les résultats de nos tests lorsque nous interrogeons le endpoint OpenAI en passant par notre applicatip
```suggestion
Voici les résultats de mes tests lorsque j'interroge le endpoint OpenAI en passant par notre application.
```

2024-01-15 08:59 UTC, jmdoudoux-sciam commented on _posts/2024-01-15-springboot-et-openai.adoc
> +image::rickenbazolo/spring_ai/demo_genai-a.png[image,width=50%,align="center"]
Les images ne sont pas lisibles. Mettre une taille à 100% et peut être utiliser un fond blanc ?

2024-01-15 09:49 UTC, ricken07 commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Nous allons comprendre l'auto-configuration fournie par Spring Boot pour nous aider à maitriser et personnaliser la configuration des composants prochainement.
Voici une reformulation de la phrase:
"Prochainement, nous explorerons l'auto-configuration fournie par Spring Boot afin de mieux comprendre et maîtrise la configuration des composants, ainsi que d'apprendre à les personnaliser."

2024-01-15 09:51 UTC, ricken07 commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Pour un projet Maven, ajouté
" il faut ajouter : " c'est OK

2024-01-15 09:52 UTC, ricken07 commented on _posts/2024-01-15-springboot-et-openai.adoc
> +image::rickenbazolo/spring_ai/demo_genai-a.png[image,width=50%,align="center"]
OK, je refais les images

2024-01-15 11:16 UTC, antoinesd requested changes
Petits détails à changer ou discuter

2024-01-15 11:16 UTC, antoinesd commented on _posts/2024-01-15-springboot-et-openai.adoc
> +:page-excerpt: L'IA s'est rapprochée de nombreux domaines, en particulier du secteur de la programmation, la prochaine vague d'application d'IA générative est appelée à se répandre dans divers langag
Tu peux peut être rajouter une ou deux phrases pour ramener l'abstract à ton sujet. Du genre:

> C'est donc aussi le cas pour Java et comme l'un des frameworks les plus populaire sur la plateforme est Spring Boot il est naturel que l'exploitation des API OpenAI arrivent également dans le modèle de programmation Spring. Cet article explore cette intégration...

Ca fait un abstract un peu plus consistant et qui introduit ton article

2024-01-15 11:16 UTC, antoinesd commented on _posts/2024-01-15-springboot-et-openai.adoc
> +Pour tester l'application, vous pouvez utiliser un client REST, dans mon cas j'utilise https://www.postman.com/[postman^]
```suggestion
Pour tester l'application, vous pouvez utiliser un client REST, dans mon cas, j'utilise https://www.postman.com/[postman^]
```

2024-01-15 15:51 UTC, ricken07 commented on _posts/2024-01-15-springboot-et-openai.adoc
> +:page-excerpt: L'IA s'est rapprochée de nombreux domaines, en particulier du secteur de la programmation, la prochaine vague d'application d'IA générative est appelée à se répandre dans divers langag
Je propose: "L'intelligence artificielle s'est rapprochée de nombreux domaines, en particulier du secteur de la programmation. La prochaine génération d'applications d'IA générative est destinée à se propager à travers divers langages de programmation. C'est également le cas pour Java, et étant donné que Spring Boot est l'un des frameworks les plus populaires sur cette plateforme, il est naturel que l'intégration des API OpenAI se fasse également dans le modèle de programmation Spring. Cet article explore cette intégration."

2024-01-16 10:19 UTC, antoinesd approved these changes

2024-01-16 10:45 UTC, merged