Article java 22 partie 1
SCIAM-FR/sciam-fr.github.io pull request #60
Opened 2024-04-07 17:35 UTC by jmdoudoux-sciam

## Suivi revue article

| Relecteur                          | Statut                                                                        | Validation                 | 
|------------------------------------|-------------------------------------------------------------------------------|----------------------------|
| @antoinesd                         | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| Ajouter la personne de votre choix | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |

## Points à prendre en compte durant la relecture
- Forme
    - tournures, oublis, passages trop lourds/indigestes, orthographe, grammaire
    - méta-données : auteur, résumé
- Fond
- Légal
    - Originalité de l'article, source des images
- SEO

2024-04-07 17:38 UTC, jmdoudoux-sciam commented
J'ai commité par erreur la modif dans le fichier gemfile, mais en vrai si elle n'a pas d'effets de bord chez d'autres qui ne sont pas sous Windows, son intégration m'éviterait d'avoir à la refaire à chaque nouvel article

2024-04-08 12:57 UTC, antoinesd requested changes
Pas beaucoup d'erreurs à se mettre sous la dent. Super article

2024-04-08 12:57 UTC, antoinesd commented on _posts/2024-04-04-nouveautes-java-22-partie1.adoc
> +Sa méthode abstraite `boolean push(T element)` permet d’envoyer éventuellement l’élément en sortie. Elle renvoie un booléen : `false` pour short cirtuiting sinon `true`
Je ne sais pas si "short circuiting" est un terme officiel mais tu ne l'as pas vraiement introduit. Sinon en français il y a "court-circuiter"

2024-04-08 12:57 UTC, antoinesd commented on _posts/2024-04-04-nouveautes-java-22-partie1.adoc
> +La méthode `invokeAll(Collection)` de l’interface `ExecutorService` lève une exception de type `InterruptedException`. La méthode `invokeAll(Collection)` était redéfinie dans la classe `ForkJoinPool`
```suggestion
La méthode `invokeAll(Collection)` de l’interface `ExecutorService` lève une exception de type `InterruptedException`. La méthode `invokeAll(Collection)` était redéfinie dans la classe `ForkJoinPool` pour ne pas ne déclarer lever d'``InterruptedException``. Dans le JDK 22, cette redéfinition a été supprimé de `ForkJoinPool`. Le code existant utilisant `ForkJoinPool::invokeAll` devra être modifié. Si le code ne souhaite pas gérer l’interruption, il pourra utiliser la méthode `invokeAllUninterruptibly()`.
```

2024-04-08 12:57 UTC, antoinesd commented on _posts/2024-04-04-nouveautes-java-22-partie1.adoc
> +Elle propose des évolutions syntaxiques et dans les API en standard, notamment L’API FFM) et en preview pour la première fois ou pour une N^eme^ preview.
```suggestion
Elle propose des évolutions syntaxiques et dans les API en standard (notamment L’API FFM) et en preview pour la première fois ou pour une N^eme^ preview.
```

2024-04-08 12:57 UTC, antoinesd commented on _posts/2024-04-04-nouveautes-java-22-partie1.adoc
> +&nbsp;
```suggestion
```

2024-04-08 13:44 UTC, jmdoudoux-sciam commented on _posts/2024-04-04-nouveautes-java-22-partie1.adoc
> +&nbsp;
C'est pour ne pas coller la dernière ligne aux boutons "suivants" et "précédent"
C'est moche mais ça fait la taf

2024-04-08 14:11 UTC, jmdoudoux-sciam commented on _posts/2024-04-04-nouveautes-java-22-partie1.adoc
> +Sa méthode abstraite `boolean push(T element)` permet d’envoyer éventuellement l’élément en sortie. Elle renvoie un booléen : `false` pour short cirtuiting sinon `true`
J'ai légèrement modifié pour mettre en français avec anglais entre parenthèses

2024-04-08 14:18 UTC, antoinesd approved these changes
LGTM

2024-04-08 14:22 UTC, antoinesd reviewed
/rebase

2024-04-08 14:27 UTC, merged