Article - Les Composants Web
SCIAM-FR/sciam-fr.github.io pull request #65
Opened 2024-04-29 10:39 UTC by kompike

## Suivi revue article

| Relecteur                          | Statut                                                                        | Validation                 | 
|------------------------------------|-------------------------------------------------------------------------------|----------------------------|
| @antoinesd                         | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| @jmdoudoux-sciam                   | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| Ajouter la personne de votre choix | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |

## Points à prendre en compte durant la relecture
- Forme
    - tournures, oublis, passages trop lourds/indigestes, orthographe, grammaire
    - méta-données : auteur, résumé
- Fond
- Légal
    - Originalité de l'article, source des images
- SEO

2024-05-02 06:11 UTC, antoinesd requested changes
Très bon article

2024-05-02 06:11 UTC, antoinesd commented on _posts/2024-04-26-composants-web.adoc
> +Pourtant, malgré cela, les composants web restent une approche populaire pour créer des applications web, et il existe de nombreuses…
```suggestion
Pourtant, malgré cela, les composants web restent une approche populaire pour créer des applications web.
La liste des acteurs les utilisant en témoigne.```

2024-05-03 07:06 UTC, antoinesd approved these changes
LGTM

2024-05-03 10:12 UTC, kompike commented on _posts/2024-04-26-composants-web.adoc
> +Fondamentalement, https://developer.mozilla.org/fr/docs/Web/API/Web_components[les composants web^] sont un ensemble d'API de la plateforme web qui permettent de créer des éléments HTML spéciaux pour
Corrigé, le lien ajouté

2024-05-03 10:12 UTC, kompike commented on _posts/2024-04-26-composants-web.adoc
> +* *Encapsulation :* Les composants web offrent une encapsulation de la fonctionnalité et du style dans une seule entité. Cette encapsulation aide à éviter les conflits de noms et les modifications no
Remplacé par `plus faciles à comprendre, à analyser et à entretenir`.

2024-05-06 15:18 UTC, jmdoudoux-sciam requested changes

2024-05-06 15:18 UTC, jmdoudoux-sciam commented on _posts/2024-04-26-composants-web.adoc
> +*Vaut-il la peine de les considérer ?* Absolument, surtout pour les composants légers utilisés dans plusieurs projets.
```suggestion

*Vaut-il la peine de les considérer ?* Absolument, surtout pour les composants légers utilisés dans plusieurs projets.
```

2024-05-06 15:18 UTC, jmdoudoux-sciam commented on _posts/2024-04-26-composants-web.adoc
> +* *http://@carbon/ibmdotcom-web-components[IBM @carbon/ibmdotcom-web-components :^]* Une bibliothèque de composants web pour les produits et plateformes IBM.
Le lien http://carbon/ibmdotcom-web-components est brisé : c'est peut être https://carbondesignsystem.com/ non ?

2024-05-06 15:20 UTC, jmdoudoux-sciam commented on _posts/2024-04-26-composants-web.adoc
> +* *http://@carbon/ibmdotcom-web-components[IBM @carbon/ibmdotcom-web-components :^]* Une bibliothèque de composants web pour les produits et plateformes IBM.
Bon article
J'ai fait quelques suggestions et commentaires. N'hésites pas si tu as des questions

2024-05-07 10:04 UTC, kompike commented on _posts/2024-04-26-composants-web.adoc
> +*https://lit.dev/[Lit^]* : successeur de Polymer par Google, Lit abstrait une grande partie du code de modèle nécessaire à la création de composants web. Il rend le développement plus efficace et off
Retiré

2024-05-07 10:06 UTC, kompike commented on _posts/2024-04-26-composants-web.adoc
> +Au cours des 15 dernières années, le paysage du développement web a considérablement changé. Des frameworks tels que Angular, React et Vue.js dominent désormais le secteur, simplifiant la vie des dév
Je suis d'accord, c'est plus un complément

2024-05-07 10:06 UTC, kompike commented on _posts/2024-04-26-composants-web.adoc
> +En outre, il convient de mentionner des instruments tels que https://hybrids.js.org/#/[Hybrids^], http://Skate.js[Skate.js^], http://Slim.js[Slim.js^], qui sont moins populaires.
Corrigé

2024-05-07 10:07 UTC, kompike commented on _posts/2024-04-26-composants-web.adoc
> +* *http://@carbon/ibmdotcom-web-components[IBM @carbon/ibmdotcom-web-components :^]* Une bibliothèque de composants web pour les produits et plateformes IBM.
> Le lien http://carbon/ibmdotcom-web-components est brisé : c'est peut être https://carbondesignsystem.com/ non ?

Corrigé

2024-05-07 10:21 UTC, kompike commented on _posts/2024-04-26-composants-web.adoc
> +* *YouTube :* Un des premiers services à migrer vers les composants web, et ils sont toujours présents dans le code source de la plateforme vidéo.
Malheureusement, il existe désormais des informations récentes à ce sujet, uniquement quelques articles sans liens et des articles et vidéos vieux de 6 ans (https://youtu.be/tNulrEbTQf8?si=LKPn9roq2P6-QiLo) selon lesquels Youtube utilise des composants Web. Mais il est possible de les voir si vous ouvrez la console de développement dans Chrome + il existe des fichiers avec des composants Web Polymer dans les ressources de la page Youtube (également disponibles dans la console de développement). Je l'ai retiré de cette section pour conserver le même style et je l'ai ajouté à la liste des autres entreprises.

2024-05-07 10:33 UTC, kompike commented on _posts/2024-04-26-composants-web.adoc
> +* *Langage de conception cohérent :* Si vous travaillez sur un projet nécessitant une cohérence dans le langage de conception à travers plusieurs applications ou équipes, les composants web peuvent a
[Un langage de conception ou vocabulaire de design](https://fr.wikipedia.org/wiki/Langage_de_conception). Dans mon article, ce sont les styles globaux de l'application, le guide de design (comme Material Design chez Google).

2024-05-07 11:39 UTC, kompike commented on _posts/2024-04-26-composants-web.adoc
> +* *Intégrations tierces :* Si vous construisez une plateforme ou un framework permettant aux développeurs tiers d'étendre sa fonctionnalité, les composants web offrent un moyen sécurisé et isolé d'in
Les styles des composants Web sont encapsulés grâce au Shadow DOM (ils sont masqués pour tous les parents du composant) et c'est l'un des principaux avantages des composants Web, car une fois créé, le composant aura la même apparence dans différents projets et systèmes. Mais en même temps, l'encapsulation est un inconvénient (du moins d'après mon expérience) : parfois, il faut vraiment ajuster un style du composant, mais ce n'est pas facile. Il est possible d'utiliser des techniques telles que [::part](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) et [:host](https://developer.mozilla.org/en-US/docs/Web/CSS/:host_function) pseudo-éléments ou en utilisant [des variables personnalisées CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties). Donc, si vous savez que vous aurez besoin d'une personnalisation des styles, il est préférable de concevoir le composant en tenant compte des techniques ci-dessus.

2024-05-07 11:49 UTC, kompike commented on _posts/2024-04-26-composants-web.adoc
> +* *Compatibilité inter-frameworks :* Les composants web offrent une méthode normalisée pour créer des composants réutilisables qui fonctionnent avec différents frameworks et bibliothèques JavaScript.
Je l'ai décrit plus en détail dans la partie "L’utilisation des composants web dans les frameworks populaires". La compatibilité dépend du framework et de la bibliothèque utilisée pour créer le composant web. Pour l'instant, la pire situation est avec React mais l'équipe React travaille sur des correctifs et la version `experimental` permet de travailler avec des composants web. Pour d'autres frameworks, quelques petits ajustements sont nécessaires, mais ce n'est pas un gros problème et (encore une fois) dépend de la bibliothèque de composants Web utilisée.
Je travaille actuellement sur un petit projet (https://github.com/kompike/stencil-wc-demo/tree/wc/bubble-chart) dans lequel j'ai créé un composant web à l'aide de Stencil et l'ai ajouté aux frameworks principaux. Je travaille ce jour sur le nettoyage du code et la documentation et j'aimerais ajouter le lien vers le code à cet article plus tard (probablement en tant que PR distinct).

2024-05-07 11:51 UTC, jmdoudoux-sciam commented on _posts/2024-04-26-composants-web.adoc
> +* *Intégrations tierces :* Si vous construisez une plateforme ou un framework permettant aux développeurs tiers d'étendre sa fonctionnalité, les composants web offrent un moyen sécurisé et isolé d'in
Oui cette dualité n'est jamais simple à gérer d'où ma question, merci pour la réponse

2024-05-07 11:51 UTC, jmdoudoux-sciam commented on _posts/2024-04-26-composants-web.adoc
> +* *Langage de conception cohérent :* Si vous travaillez sur un projet nécessitant une cohérence dans le langage de conception à travers plusieurs applications ou équipes, les composants web peuvent a
ok, merci

2024-05-07 11:52 UTC, jmdoudoux-sciam commented on _posts/2024-04-26-composants-web.adoc
> +* *YouTube :* Un des premiers services à migrer vers les composants web, et ils sont toujours présents dans le code source de la plateforme vidéo.
ok

2024-05-07 11:54 UTC, jmdoudoux-sciam approved these changes

2024-05-07 13:56 UTC, merged