Article - Génération de tests unitaires en Java avec Randoop
SCIAM-FR/sciam-fr.github.io pull request #68
Opened 2024-05-23 11:39 UTC by idr77

## Suivi revue article

| Relecteur                          | Statut                                                                        | Validation                 | 
|------------------------------------|-------------------------------------------------------------------------------|----------------------------|
| @antoinesd                         | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| @jmdoudoux-sciam                   | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| Ajouter la personne de votre choix | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |

## Points à prendre en compte durant la relecture
- Forme
    - tournures, oublis, passages trop lourds/indigestes, orthographe, grammaire
    - méta-données : auteur, résumé
- Fond
- Légal
    - Originalité de l'article, source des images
- SEO

2024-05-29 05:46 UTC, antoinesd requested changes
Article très intéressant mais je reste un peu sur ma faim : de ce que j'en comprend Randoop ne peut pas être intégré dans la chaine CI/CD comme tu le dis puisqu'il faut revoir les tests générés. en revanche le tooling coté IDE pourrait être intéressant (quid du plugin Eclipse) ?
J'ai rajouté les délimiter de blocs de code pour te permettre d'aérer le code. Je pense que c'est une bonne pratique (comme les {} après un if même avec une instruction ;-).

2024-05-29 05:46 UTC, antoinesd commented on _posts/2024-05-22-generation-tests-unitaires.adoc
> +Randoop générera alors deux types de tests unitaires écrits dans deux fichiers distincts au format JUnit :
Junit 4 ou 5 ? Je peux choisir ?

2024-05-29 05:46 UTC, antoinesd commented on _data/authors.yml
> -    linkedin: "pierre-cheucle"
Pourquoi avr effacé le lien LinkedIn de Pierre ?

2024-05-31 16:34 UTC, idr77 commented on _posts/2024-05-22-generation-tests-unitaires.adoc
> +Indique à Randoop de ne pas prendre en compte les méthodes qui correspondent au pattern.
Oui, le pattern correspond à une regexp

2024-05-31 17:04 UTC, idr77 commented on _posts/2024-05-22-generation-tests-unitaires.adoc
> +Randoop générera alors deux types de tests unitaires écrits dans deux fichiers distincts au format JUnit :
Oui, on peut utiliser les deux versions.

2024-05-31 17:05 UTC, idr77 commented on _data/authors.yml
> -    linkedin: "pierre-cheucle"
C'est une erreur en rebasant ma branche, je corrige ça :)

2024-06-05 07:48 UTC, antoinesd approved these changes
LGTM

2024-06-05 07:49 UTC, merged