Article angular16
SCIAM-FR/sciam-fr.github.io pull request #8
Opened 2023-09-11 12:43 UTC by Khaoulaa

## Suivi revue article

| Relecteur                          | Statut                                                                        | Validation                 | 
|------------------------------------|-------------------------------------------------------------------------------|----------------------------|
| @antoinesd                         | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| @jmdoudoux_sciam                   | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| Ajouter la personne de votre choix | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |

## Points à prendre en compte durant la relecture
- Forme
    - tournures, oublis, passages trop lourds/indigestes, orthographe, grammaire
    - méta-données : auteur, résumé
- Fond
- Légal
    - Originalité de l'article, source des images
- SEO

2023-09-13 19:24 UTC, jmdoudoux-sciam commented
J'ai commité deux modifs dans le fichier _authors.yml suite à la PR 11
J'ai aussi mis à jour le lien linkedin avec la bonne valeur

2023-09-20 16:02 UTC, antoinesd requested changes
Ton article est intéressant mais encore trop en style "télégraphique" et avec beaucoup de fautes. J'ai corrigé ce que j'ai pu (j'espère ne pas avoir fait de contre sens). Quelqu'un de débutant sous angulaire devrait arriver à suive. Je ne suis pas sûr que ce soit le cas.
Essaie de faire des phrases courtes et d'introduire tes concepts un peu plus.

2023-09-20 16:02 UTC, antoinesd requested changes
Ton article est intéressant mais encore trop en style "télégraphique" et avec beaucoup de fautes. J'ai corrigé ce que j'ai pu (j'espère ne pas avoir fait de contre sens). Quelqu'un de début sous angulaire devrait arriver à suive. Je ne suis pas sûr que ce soit le cas.
Essaie de faire des phrases courtes et d'introduire tes concepts un peu plus.

2023-09-20 20:23 UTC, bmscomp commented on images/khaoulamrabet/signal.png
Est ce que le fait de souligner en rouge les les titres est voulu ou c'est juste le correcteur

2023-09-20 21:23 UTC, jmdoudoux-sciam commented on images/khaoulamrabet/signal.png
C'est fort probablement le correcteur lors de la capture.

2023-09-22 15:56 UTC, Khaoulaa reviewed
correctifs après review

2023-10-02 20:24 UTC, jmdoudoux-sciam commented on _posts/2023-09-08-nouveautes-angular-16.adoc
> +  constructor() {
```suggestion

  constructor() {
```

2023-10-02 20:24 UTC, jmdoudoux-sciam commented on _posts/2023-09-08-nouveautes-angular-16.adoc
> +
```suggestion
```

2023-10-02 20:24 UTC, jmdoudoux-sciam commented on _posts/2023-09-08-nouveautes-angular-16.adoc
> +
```suggestion
```

2023-10-02 20:24 UTC, jmdoudoux-sciam commented on _posts/2023-09-08-nouveautes-angular-16.adoc
> +
```suggestion
```

2023-10-02 20:24 UTC, jmdoudoux-sciam commented on _posts/2023-09-08-nouveautes-angular-16.adoc
> +export class UserComponent {
```suggestion

export class UserComponent {
```

2023-10-02 20:24 UTC, jmdoudoux-sciam commented on _posts/2023-09-08-nouveautes-angular-16.adoc
> +<1> Avec Input on récupére directement le paramétre de route.
```suggestion
<1> Avec Input on récupère directement le paramètre de routage.
```

2023-10-02 20:24 UTC, jmdoudoux-sciam commented on _posts/2023-09-08-nouveautes-angular-16.adoc
> +== Rxjs-interpo
```suggestion
== Le module Rxjs-interpo
```

2023-10-02 20:24 UTC, jmdoudoux-sciam commented on _posts/2023-09-08-nouveautes-angular-16.adoc
> +Un nouveau module d'angular propose des opérations qui conviennent avec le système de réactivité basé sur le signal d'Angular.
```suggestion
Un nouveau module d'Angular propose des opérations qui conviennent avec le système de réactivité basé sur les Signals d'Angular.
```

2023-10-02 20:24 UTC, jmdoudoux-sciam commented on _posts/2023-09-08-nouveautes-angular-16.adoc
> +`TakeUntilDestroy`:  Opérateur qui complète l'Observable lorsque le contexte appelant (composant, directive, service, etc.) est détruit.
```suggestion
`TakeUntilDestroy`:  un opérateur qui complète l'Observable lorsque le contexte appelant (composant, directive, service, etc.) est détruit.
```

2023-10-02 20:24 UTC, jmdoudoux-sciam commented on _posts/2023-09-08-nouveautes-angular-16.adoc
> +
```suggestion
```

2023-10-02 20:24 UTC, jmdoudoux-sciam commented on _posts/2023-09-08-nouveautes-angular-16.adoc
> +Cette nouvelle `version 16` apporte deux amélioration majeures :
```suggestion
Cette nouvelle version 16 apporte deux améliorations majeures : 
```

2023-10-02 20:24 UTC, jmdoudoux-sciam commented on _posts/2023-09-08-nouveautes-angular-16.adoc
> +* l'hydratation qui réduit le temps de chargement des applications
```suggestion

* l'hydratation qui réduit le temps de chargement des applications
```

2023-10-02 20:24 UTC, jmdoudoux-sciam commented on _posts/2023-09-08-nouveautes-angular-16.adoc
> +Comme le montre les exemples de cet articles, le code produit avec la version 16 est moins compliqué et nettement plus expressif, ce qui améliore grandement l'expérience de développement.
```suggestion
Comme le montre les exemples de cet article, le code produit avec la version 16 est moins compliqué et nettement plus expressif, ce qui améliore grandement l'expérience de développement.
```

2023-10-16 16:04 UTC, antoinesd approved these changes

2023-10-16 16:05 UTC, merged