Du Concept à l'Action : Le Function Calling des LLM et son Utilisation avec Spring AI - Partie 1
SCIAM-FR/sciam-fr.github.io pull request #89
Opened 2024-08-25 17:50 UTC by ricken07

## Suivi revue article

| Relecteur                          | Statut                                                                        | Validation                 | 
|------------------------------------|-------------------------------------------------------------------------------|----------------------------|
| @antoinesd                         | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| @jmdoudoux-sciam                   | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| Ajouter la personne de votre choix | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |

## Points à prendre en compte durant la relecture
- Forme
    - tournures, oublis, passages trop lourds/indigestes, orthographe, grammaire
    - méta-données : auteur, résumé
- Fond
- Légal
    - Originalité de l'article, source des images
- SEO

2024-08-26 08:28 UTC, antoinesd requested changes
Pas la peine de mettre 3 retour charriots pour changer de paragraphe, 2 suffisent : 1 à la fin du paragraphe plus un supplémentaire avant de commencer le nouveau paragraphe.

2024-08-26 08:28 UTC, antoinesd commented on _posts/2024-08-30-function-calling-llm-partie1.adoc
> +Le Function Calling représente un lien essentiel entre les capacités conversationnelles des modèles de language de grande taille (LLM) et l'accès à des fonctionnalités techniques spécialisées via des
```suggestion
Le Function Calling représente un lien essentiel entre les capacités conversationnelles des modèles de langage de grande taille (LLM) et l'accès à des fonctionnalités techniques spécialisées via des outils (*Tools*) externes.
```

2024-08-26 08:28 UTC, antoinesd commented on _posts/2024-08-30-function-calling-llm-partie1.adoc
> +Le Function Calling relie les LLM (Large Language Models) au concept des agents IA en leur permettant de devenir plus autonomes et actifs dans les systèmes. Grâce à cette fonctionnalité, les LLM ne s
```suggestion
Le Function Calling relie les LLM (Large Language Models) au concept des agents IA en leur permettant de devenir plus autonomes et actifs dans les systèmes.
Grâce à cette fonctionnalité, les LLM ne se contentent plus de comprendre et répondre les demandes des utilisateurs, mais peuvent aussi exécuter des actions en appelant des fonctions spécifiques. Cela les transforme en véritables agents intelligents, capables de gérer des tâches complexes, de s'adapter aux contextes variés, et de mieux interagir avec les systèmes informatiques.
Cette autonomie, tout en restant sous le contrôle des développeurs, fait des LLM avec Function Calling un outil puissant pour créer des agents IA avancés.
*Dans le second article, nous explorerons comment intégrer le Function Calling dans une application Java avec Spring AI.*
```

2024-08-26 08:28 UTC, antoinesd commented on _posts/2024-08-30-function-calling-llm-partie1.adoc
> +Le Function Calling relie les LLM (Large Language Models) au concept des agents IA en leur permettant de devenir plus autonomes et actifs dans les systèmes. Grâce à cette fonctionnalité, les LLM ne s
Une phrase par ligne ;-)

2024-08-26 13:23 UTC, antoinesd approved these changes

2024-08-27 18:25 UTC, jmdoudoux-sciam requested changes

2024-08-27 18:25 UTC, jmdoudoux-sciam commented on _posts/2024-08-30-function-calling-llm-partie1.adoc
> +Voici un shémas qui illustre le fonctionnement du *Function Calling* dans un contexte conversationnel :
```suggestion
Voici un schéma qui illustre le fonctionnement du *Function Calling* dans un contexte conversationnel :
```

2024-08-27 18:25 UTC, jmdoudoux-sciam commented on _posts/2024-08-30-function-calling-llm-partie1.adoc
> +== Cas d'usage Théoriques
```suggestion
== Des cas d'usage théoriques
```

2024-08-27 18:25 UTC, jmdoudoux-sciam commented on _posts/2024-08-30-function-calling-llm-partie1.adoc
> +== Fuction Calling, Tools et Agents IA
```suggestion
== Le Fuction Calling, les Tools et les Agents IA
```

2024-08-27 18:25 UTC, jmdoudoux-sciam commented on _posts/2024-08-30-function-calling-llm-partie1.adoc
> +Ce mécanisme permet aux LLM de dépasser leur rôle traditionnel de simples générateurs de texte pour devenir de véritables *Agents IA*, _des entités capables de comprendre une intention, de mobiliser
```suggestion
Ce mécanisme permet aux LLM de dépasser leur rôle traditionnel de simples générateurs de texte pour devenir de véritables *Agents IA*, des entités capables de comprendre une intention, de mobiliser le bon outil, et d'exécuter une action précise pour atteindre un résultat optimal.
```

2024-08-27 18:25 UTC, jmdoudoux-sciam commented on _posts/2024-08-30-function-calling-llm-partie1.adoc
> +*Dans le second article, nous explorerons comment intégrer le Function Calling dans une application Java avec Spring AI.*
```suggestion
Dans le second article, nous explorerons comment intégrer le Function Calling dans une application Java avec Spring AI.
```

2024-08-28 07:02 UTC, jmdoudoux-sciam approved these changes

2024-08-28 07:32 UTC, merged