Article Function Calling LLM partie 2
SCIAM-FR/sciam-fr.github.io pull request #95
Opened 2024-09-07 22:10 UTC by ricken07

## Suivi revue article

| Relecteur                          | Statut                                                                        | Validation                 | 
|------------------------------------|-------------------------------------------------------------------------------|----------------------------|
| @antoinesd                         | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| @jmdoudoux-sciam                   | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| Ajouter la personne de votre choix | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |

## Points à prendre en compte durant la relecture
- Forme
    - tournures, oublis, passages trop lourds/indigestes, orthographe, grammaire
    - méta-données : auteur, résumé
- Fond
- Légal
    - Originalité de l'article, source des images
- SEO

2024-09-11 01:17 UTC, antoinesd commented on _posts/2024-09-08-function-calling-llm-partie2.adoc
> +Au niveau ChatClient.Builder, vous pouvez spécifier le prompt par défaut. https://docs.spring.io/spring-ai/reference/1.0/api/chatclient.html#_other_defaults[consulter les valeurs par défaut^] du prom
```suggestion
Au niveau ChatClient. Builder, vous pouvez spécifier le prompt par défaut. https://docs.spring.io/spring-ai/reference/1.0/api/chatclient.html#_other_defaults[consulter les valeurs par défaut^] du prompt.
```

2024-09-11 01:32 UTC, antoinesd requested changes

2024-09-11 01:32 UTC, antoinesd commented on _posts/2024-09-08-function-calling-llm-partie2.adoc
> +Cette API permet de créer des prompts, constituées de messages, qui sont envoyées au modèle pour guider sa réponse et son comportement.
```suggestion
Cette API permet de créer des prompts, constitués de messages, qui sont envoyés au modèle pour guider sa réponse et son comportement.
```

2024-09-11 01:32 UTC, antoinesd commented on _posts/2024-09-08-function-calling-llm-partie2.adoc
> +Spring AI simplifie l'invocation de fonctions en vous permettant d'enregistrer une https://docs.oracle.com/javase/8/docs/api/?java/util/function/Function.html[Java Function^] en tant que `@Bean` et d
pourquoi pointer vers la doc de java 8 et pas 11 ou 17 ? Je sais l'entrée est probablement la même mais ça risque de prêter à confusion sur le niveu de Java supporté par Spring AI

2024-09-11 01:32 UTC, antoinesd commented on _posts/2024-09-08-function-calling-llm-partie2.adoc
> +NOTE: Les modèles (LLM) sont formé pour détecter quand appeler une fonction et répondre avec un `JSON` conforme à la signature de la fonction définie.
```suggestion
NOTE: Les modèles (LLM) sont formés pour détecter quand appeler une fonction et répondre avec un `JSON` conforme à la signature de la fonction définie.
```

2024-09-11 01:32 UTC, antoinesd commented on _posts/2024-09-08-function-calling-llm-partie2.adoc
> +NOTE: Les aspects sécurité et confidentialité de données ne sont pas prise en charge, pour garder l’exemple simple.
```suggestion
NOTE: Les aspects sécurité et confidentialité de données ne sont pas pris en charge, pour garder l’exemple simple.
```

2024-09-11 10:57 UTC, ricken07 commented on _posts/2024-09-08-function-calling-llm-partie2.adoc
> +Au niveau ChatClient.Builder, vous pouvez spécifier le prompt par défaut. https://docs.spring.io/spring-ai/reference/1.0/api/chatclient.html#_other_defaults[consulter les valeurs par défaut^] du prom
Ici, je fais référence au composant builder du ChatClient

2024-09-11 11:00 UTC, ricken07 commented on _posts/2024-09-08-function-calling-llm-partie2.adoc
> +Spring AI simplifie l'invocation de fonctions en vous permettant d'enregistrer une https://docs.oracle.com/javase/8/docs/api/?java/util/function/Function.html[Java Function^] en tant que `@Bean` et d
OK, je vais pointer vers la version récente de Java

2024-09-11 12:07 UTC, jmdoudoux-sciam requested changes

2024-09-11 12:07 UTC, jmdoudoux-sciam commented on _posts/2024-09-08-function-calling-llm-partie2.adoc
> +Pour envoyer une ou plusieurs fonctions dans le prompt, Spring AI simplifie le processus en permettant de définir un @Bean qui retourne une `java.util.Function`, comme nous l'avons fait pour notre fo
```suggestion
Pour envoyer une ou plusieurs fonctions dans le prompt, Spring AI simplifie le processus en permettant de définir une méthode annotée `@Bean` qui retourne une `java.util.Function`, comme nous l'avons fait pour notre fonction `obtenirStatutCommande`. Il suffit ensuite de fournir le nom du bean défini dans le contexte de l'application en option via `defaultFunctions()` ou `functions()` lors de l'appel au ChatClient.
```

2024-09-11 13:26 UTC, jmdoudoux-sciam requested changes

2024-09-11 13:26 UTC, jmdoudoux-sciam commented on _posts/2024-09-08-function-calling-llm-partie2.adoc
> +== L'envoie de la fonction au LLM
```suggestion
== L'envoi de la fonction au LLM
```

2024-09-11 14:11 UTC, jmdoudoux-sciam approved these changes

2024-09-12 06:09 UTC, antoinesd approved these changes
LGTM

2024-09-12 06:15 UTC, merged