Article - gRPC et Protocol Buffers
SCIAM-FR/sciam-fr.github.io pull request #99
Opened 2024-09-17 14:12 UTC by kompike

## Suivi revue article

| Relecteur                          | Statut                                                                        | Validation                 | 
|------------------------------------|-------------------------------------------------------------------------------|----------------------------|
| @antoinesd                         | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| @jmdoudoux-sciam                   | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |
| Ajouter la personne de votre choix | <ul><li>- [x] A faire</li><li>- [ ] En cours</li><li>- [ ] Terminée</li></ul> | <ul><li>- [ ] OK</li></ul> |

## Points à prendre en compte durant la relecture
- Forme
    - tournures, oublis, passages trop lourds/indigestes, orthographe, grammaire
    - méta-données : auteur, résumé
- Fond
- Légal
    - Originalité de l'article, source des images
- SEO

2024-09-18 15:39 UTC, jmdoudoux-sciam requested changes

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +Il semble très difficile de trouver un développeur qui n'ait jamais entendu parler de REST. Ce n'est pas surprenant : ce style (ou plus précisément, cette approche de la construction de connexions ré
```suggestion
Il semble très difficile de trouver un développeur qui n'ait jamais entendu parler de REST. Ce n'est pas surprenant : ce style (ou plus précisément, cette approche de la construction de connexions réseau et de protocoles) est depuis de nombreuses années la norme de référence dans le développement logiciel. Sa simplicité d'utilisation intuitive et son abstraction par rapport aux langages de programmation spécifiques font de REST (couplé à JSON) le choix idéal pour tout développeur confronté à des échanges réseau (et, selon mon humble avis, cela concerne la grande majorité des développeurs).

```

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +Bien sûr, REST n'est pas le seul outil pour transférer des données. Avec l'évolution dynamique du monde de la programmation et de l'architecture logicielle, de nouvelles alternatives ont vu le jour p
```suggestion
Bien sûr, REST n'est pas le seul outil pour transférer des données. Avec l'évolution dynamique du monde de la programmation et de l'architecture logicielle, de nouvelles alternatives ont vu le jour pour répondre aux besoins actuels des développeurs. GraphQL, WebSockets, MQTT, Event-Driven Architecture : ces outils et paradigmes sont également largement utilisés.

```

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +Cependant, dans cet article, j’aimerais attirer votre attention sur une autre approche intéressante pour créer des connexions réseau entre les services, à savoir gRPC et son partenaire inséparable -
```suggestion
Cependant, dans cet article, j’aimerais attirer votre attention sur une autre approche intéressante pour créer des échanges réseau entre les services, à savoir gRPC et son partenaire inséparable - Protocol Buffers, ou simplement Protobuf. À ce stade, beaucoup d'entre vous se demanderont : pourquoi j'aurais besoin de quelque chose dont je n'ai probablement jamais entendu parler auparavant, et qui peut être facilement résolu en utilisant l'approche REST ? C’est à cette question que nous allons essayer de répondre ci-dessous.

```

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +Selon le site Web officiel, gRPC est un framework RPC moderne, performant et open-source, capable de fonctionner dans n’importe quel environnement. Le concept de RPC (Remote Procedure Call) n’est pas
Ajouter un lien vers le site web ?

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +Les Protocol Buffers (ou simplement Protobuf) sont un mécanisme de sérialisation de données et un langage de description d'interfaces, développés par Google pour sérialiser des données structurées. I
automatiquement ? vraiment ?

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +Donc, ce qu’on voit :
Peut être utiliser des callouts pour faciliter la lisibilité ?

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +Comme dans l'exemple précédent, on commence par la définition de la version de la syntaxe et du package, puis on voit une nouveauté : nous importons le modèle d’utilisateur créé précédemment à partir
idem peut être utilisation de callouts ?

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +Voilà donc tout ce qu’il faut savoir pour créer un service gRPC. Ensuite, je propose de découvrir les avantages de cette approche et de la comparer au standard largement reconnu qu’est REST.
Peut être ajouter un exemple de code généré à partir de la description ?

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +* Implémentation plus complexe : L'utilisation de gRPC et de Protobuf nécessitera plus de temps et d'efforts à maîtriser que l'utilisation d'un API REST classique.
```suggestion
* Implémentation plus complexe : L'utilisation de gRPC et de Protobuf nécessitera plus de temps et d'efforts à maîtriser que l'utilisation d'une API REST classique.

```

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +* Typage strict : L'utilisation de fichiers proto assure une définition claire de la structure des données, ce qui aide à prévenir les erreurs et à améliorer la qualité du code.
```suggestion
* Typage strict : l'utilisation de fichiers proto assure une définition claire de la structure des données, ce qui aide à prévenir les erreurs et à améliorer la qualité du code.

```

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +* Taille des messages réduite : L'utilisation d'un format binaire permet de transmettre des données de manière plus compacte, ce qui réduit la charge sur le réseau et rend le transfert de données plu
```suggestion
* Taille des messages réduite : l'utilisation d'un format binaire permet de transmettre des données de manière plus compacte, ce qui réduit la charge sur le réseau et rend le transfert de données plus efficace.

```

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +* Implémentation plus complexe : L'utilisation de gRPC et de Protobuf nécessitera plus de temps et d'efforts à maîtriser que l'utilisation d'un API REST classique.
```suggestion
* Implémentation plus complexe : l'utilisation de gRPC et de Protobuf nécessitera plus de temps et d'efforts à maîtriser que l'utilisation d'un API REST classique.

```

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +* Écosystème limité et support dans les navigateurs : L'écosystème d'outils et de bibliothèques prenant en charge gRPC peut être plus restreint que pour les API REST (par exemple, Swagger, frameworks
```suggestion
* Écosystème limité et support dans les navigateurs : l'écosystème d'outils et de bibliothèques prenant en charge gRPC peut être plus restreint que pour les API REST (par exemple, Swagger, frameworks de test, etc.). De plus, gRPC n'est pas pris en charge par les navigateurs sans outils ou serveurs proxy supplémentaires.

```

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +* Difficulté d'analyse des données transmises : Le format binaire des données peut compliquer le processus de débogage et d'analyse des messages.
```suggestion
* Difficulté d'analyse des données transmises : le format binaire des données peut compliquer le processus de débogage et d'analyse des messages.

```

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +* Applications mobiles et IoT : Le format binaire compact de Protobuf est particulièrement utile pour les applications mobiles et IoT, où la bande passante et les performances sont des enjeux critiqu
```suggestion
* Applications mobiles et IoT : le format binaire compact de Protobuf est particulièrement utile pour les applications mobiles et IoT, où la bande passante et les performances sont des enjeux critiques.

```

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +* Applications Web et services fonctionnant principalement via un navigateur Web : gRPC n'est pas entièrement pris en charge par les navigateurs modernes qui utilisent généralement HTTP/1.1 au lieu d
les navigateurs modernes qui utilisent généralement HTTP/1.1 au lieu de HTTP/2 : est toujours vraie ?

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +* Transmission de gros volumes de données sur le réseau : gRPC transfère les données dans un format binaire et peut utiliser la mise en cache en cours de processus. La performance de ce protocole peu
(donc de grandes quantités de données peuvent toujours être essayées de transmettre) : revoir la formulation

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +|Format de données |Protocol Buffers (format binaire) |JSON (format texte)
REST n'impose pas JSON, aucun format d'ailleurs, mais JSON est le plus utilisé

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +|===
il manque peut être dans ce tableau RPC vs gestion de ressources avec un jeu de verbes standardisé

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +|Protocole de transport |HTTP/2 |HTTP/1.1
REST n'impose pas HTTP/1.1, il faut que le protocole utilisé respecte les contraintes REST, et actuellement seul HTTP les respecte que cela soit la version 1.1 ou 2.0

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +== Solution hybride
Alors je pense définitivement que tu passes à côté d'un des grands intérêts de gRPC : le RPC. 
C'est un vrai retour en arrière par rapport à REST qui est effectivement très simple mais aussi parfois très limitant dans son approche manipulation de ressources

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +:showtitle:
D'une manière générale : 
- ne pas mettre de majuscules après un deux points (j'ai fait des suggestions sur certains mais pas tous)
- mettre chaque phrase sur une ligne dédiée : cela facilite la revue et les suggestions (j'anticipe cette remarque de la part  de @antoinesd ;-) )

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +gRPC est un protocole réseau assez intéressant et en même temps un peu inhabituel et complexe. Bien sûr, il ne peut en aucun cas remplacer REST, mais il n'est pas conçu pour cela non plus. gRPC est u
en même temps un peu inhabituel et complexe : pour ceux qui n'ont jamais fait de RPC ;-)

2024-09-18 15:39 UTC, jmdoudoux-sciam commented on _posts/2024-09-17-grpc-protobuf.adoc
> +Je voudrais également souligner Protobuf. Cette technologie n'est pas seulement à la base du framework gRPC, mais peut aussi être utilisée indépendamment (y compris dans les projets web), offrant une
Oui c'est une solution de serialisation d'une manière générale comme JSON

2024-09-28 01:18 UTC, bmscomp commented on _posts/2024-09-17-grpc-protobuf.adoc
> +GraphQL, WebSockets, MQTT, Event-Driven Architecture : ces outils et paradigmes sont également largement utilisés.
Je propose d'ajouter `SOAP`  a cette liste au lieux de `Event-Driven Architecture`

2024-10-07 16:47 UTC, kompike commented
@jmdoudoux-sciam @bmscomp @antoinesd Commentaires corrigés, PTAL

2024-10-19 08:32 UTC, antoinesd commented
Hello @kompike. Selon toi, ton article est prêt à être publié ?

2024-10-19 08:57 UTC, jmdoudoux-sciam commented
Ma revue n'est pas finalisée car il y a deux commentaires sans réponse

2024-10-20 15:03 UTC, kompike commented on _posts/2024-09-17-grpc-protobuf.adoc
> +|===
J'ai ajouté la ligne `Contrats d’API` pour ça.

2024-10-20 16:41 UTC, kompike commented on _posts/2024-09-17-grpc-protobuf.adoc
> +== Solution hybride
J'ai ajouté un paragraphe séparé sur RPC.

2024-10-20 16:43 UTC, kompike commented
> Ma revue n'est pas finalisée car il y a deux commentaires sans réponse

@jmdoudoux-sciam  Désolé, je les ai manqués, ils sont corrigés maintenant

2024-10-20 16:58 UTC, kompike commented
> Hello @kompike. Selon toi, ton article est prêt à être publié ? @jmdoudoux-sciam, ta revue peut être finalisée ou il y a encore des choses à voir

Salut @antoinesd. Je l'ai relu plusieurs fois et ajouté les images et notes manquantes. De mon côté, l'article me semble bon. En tout cas, j'aimerais entendre tes commentaires ou suggestions pour l'améliorer.

2024-12-04 11:33 UTC, jmdoudoux-sciam approved these changes

2024-12-05 13:57 UTC, antoinesd requested changes
C'est presque bon. Le principal problème est lié au format de la vignette ;-)

2024-12-05 13:57 UTC, antoinesd commented on images/vignettes/gRPC_article_logo.png
Ta vignette est trop haute (bug sur l'affichage de la homepage). Pourrais-tu juste mettre le logo gRPC ?

2024-12-06 08:21 UTC, kompike commented
> C'est presque bon. Le principal problème est lié au format de la vignette ;-)

@antoinesd Commentaires corrigés, PTAL

2024-12-06 08:31 UTC, antoinesd approved these changes

2024-12-06 08:31 UTC, antoinesd commented
/rebase

2024-12-06 10:51 UTC, merged